import pandas as pd
from datetime import datetime
from utils import DataManagement

def crear_datos_para_streamlit():
    """Crear datos de ejemplo para que se vean en Streamlit Cloud"""
    
    dm = DataManagement()
    
    # Datos de ejemplo completos
    datos_ejemplo = [
        {
            "Curso": "EF 1A",
            "Trimestre": "1 Trimestre", 
            "Apellido y Nombre": "García López, María",
            "Asistencia": "18/20",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Diagnóstico",
            "Evaluación 1": "Test Inicial",
            "Calificación 1": "B",
            "Evaluación 2": "Evaluación Escrita",
            "Calificación 2": "MB",
            "Evaluación 3": "Trabajo Práctico",
            "Calificación 3": "B",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 7.67,
            "Observaciones": "Alumna aplicada, buena participación",
            "Fecha Registro": "2024-03-18 10:30:00"
        },
        {
            "Curso": "EF 1A",
            "Trimestre": "1 Trimestre",
            "Apellido y Nombre": "Rodríguez Pérez, Juan",
            "Asistencia": "15/20",
            "Nota Asistencia": "MB (8)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Físico",
            "Evaluación 1": "Test Resistencia",
            "Calificación 1": "R+",
            "Evaluación 2": "Fuerza Superior",
            "Calificación 2": "B",
            "Evaluación 3": "Velocidad",
            "Calificación 3": "B",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 6.33,
            "Observaciones": "Buena condición física",
            "Fecha Registro": "2024-03-18 10:35:00"
        },
        {
            "Curso": "EF 2A",
            "Trimestre": "1 Trimestre",
            "Apellido y Nombre": "Martínez Sánchez, Ana",
            "Asistencia": "20/20",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Técnico",
            "Evaluación 1": "Ejecución Básica",
            "Calificación 1": "MB",
            "Evaluación 2": "Técnica Avanzada",
            "Calificación 2": "MB",
            "Evaluación 3": "Juego Aplicado",
            "Calificación 3": "Ex",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 8.33,
            "Observaciones": "Excelente técnica, liderazgo",
            "Fecha Registro": "2024-03-18 10:40:00"
        },
        {
            "Curso": "EF 1B",
            "Trimestre": "2 Trimestre",
            "Apellido y Nombre": "López Gómez, Carlos",
            "Asistencia": "16/22",
            "Nota Asistencia": "MB (8)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Físico",
            "Evaluación 1": "Velocidad 40m",
            "Calificación 1": "B",
            "Evaluación 2": "Salto Vertical",
            "Calificación 2": "MB",
            "Evaluación 3": "Abdominales",
            "Calificación 3": "B",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 7.33,
            "Observaciones": "Buena evolución física",
            "Fecha Registro": "2024-03-18 10:45:00"
        },
        {
            "Curso": "EF 1B",
            "Trimestre": "3 Trimestre",
            "Apellido y Nombre": "Fernández Torres, Laura",
            "Asistencia": "21/21",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Diagnóstico",
            "Evaluación 1": "Test Inicial",
            "Calificación 1": "Ex",
            "Evaluación 2": "Evaluación Escrita",
            "Calificación 2": "MB",
            "Evaluación 3": "Trabajo Grupal",
            "Calificación 3": "Ex",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 8.67,
            "Observaciones": "Alumna destacada, excelente rendimiento",
            "Fecha Registro": "2024-03-18 10:50:00"
        },
        {
            "Curso": "EF 2B",
            "Trimestre": "3 Trimestre",
            "Apellido y Nombre": "Giménez Ruiz, Pedro",
            "Asistencia": "8/21",
            "Nota Asistencia": "M (5)",
            "Evaluaciones": 2,
            "Tipo Evaluación": "Físico",
            "Evaluación 1": "Test Resistencia",
            "Calificación 1": "M",
            "Evaluación 2": "Fuerza",
            "Calificación 2": "R-",
            "Evaluación 3": "",
            "Calificación 3": "",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 4.75,
            "Observaciones": "Asistencia muy deficiente",
            "Fecha Registro": "2024-03-18 10:55:00"
        },
        {
            "Curso": "TD 2A",
            "Trimestre": "1 Trimestre",
            "Apellido y Nombre": "Sánchez Morales, Sofía",
            "Asistencia": "17/20",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Desempeño Global",
            "Evaluación 1": "Participación",
            "Calificación 1": "B",
            "Evaluación 2": "Compromiso",
            "Calificación 2": "MB",
            "Evaluación 3": "Trabajo en Equipo",
            "Calificación 3": "B",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 7.33,
            "Observaciones": "Buena actitud, colaboradora",
            "Fecha Registro": "2024-03-18 11:00:00"
        },
        {
            "Curso": "TD 2A",
            "Trimestre": "2 Trimestre",
            "Apellido y Nombre": "Díaz Herrera, Miguel",
            "Asistencia": "20/22",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Diagnóstico",
            "Evaluación 1": "Análisis Inicial",
            "Calificación 1": "MB",
            "Evaluación 2": "Identificación Problemas",
            "Calificación 2": "B",
            "Evaluación 3": "Propuestas Solución",
            "Calificación 3": "MB",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 7.67,
            "Observaciones": "Buena capacidad analítica",
            "Fecha Registro": "2024-03-18 11:05:00"
        },
        {
            "Curso": "TD 2B",
            "Trimestre": "3 Trimestre",
            "Apellido y Nombre": "Romero Castro, Elena",
            "Asistencia": "19/21",
            "Nota Asistencia": "Ex (10)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Técnico",
            "Evaluación 1": "Fundamentos",
            "Calificación 1": "Ex",
            "Evaluación 2": "Técnica Individual",
            "Calificación 2": "MB",
            "Evaluación 3": "Juego Colectivo",
            "Calificación 3": "Ex",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 8.67,
            "Observaciones": "Excelente técnica y liderazgo",
            "Fecha Registro": "2024-03-18 11:10:00"
        },
        {
            "Curso": "EF 2A",
            "Trimestre": "2 Trimestre",
            "Apellido y Nombre": "Vargas Mendoza, Diego",
            "Asistencia": "12/22",
            "Nota Asistencia": "MB (8)",
            "Evaluaciones": 3,
            "Tipo Evaluación": "Físico",
            "Evaluación 1": "Condición General",
            "Calificación 1": "R+",
            "Evaluación 2": "Resistencia",
            "Calificación 2": "B",
            "Evaluación 3": "Fuerza",
            "Calificación 3": "R+",
            "Evaluación 4": "",
            "Calificación 4": "",
            "Evaluación 5": "",
            "Calificación 5": "",
            "Evaluación 6": "",
            "Calificación 6": "",
            "Nota Final": 6.33,
            "Observaciones": "Necesita mejorar asistencia",
            "Fecha Registro": "2024-03-18 11:15:00"
        }
    ]
    
    # Guardar todos los datos
    for datos in datos_ejemplo:
        dm.save_student_data(datos)
        print(f"Guardado: {datos['Apellido y Nombre']} - {datos['Curso']}")
    
    print(f"\nTotal de datos de ejemplo creados: {len(datos_ejemplo)}")
    print("Estos datos ahora se verán en Streamlit Cloud")

if __name__ == "__main__":
    crear_datos_para_streamlit()
